# Generated by Django 2.2.5 on 2020-09-29 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
        ('hospital', '0019_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.City'),
        ),
    ]
