# Generated by Django 2.2.5 on 2020-09-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_donor_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='group',
            field=models.CharField(blank=True, default='n/a', max_length=10, null=True),
        ),
    ]
